"""models

Revision ID: 46d05bb0e36b
Revises: 
Create Date: 2023-05-05 13:36:46.404750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46d05bb0e36b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(), nullable=False),
    sa.Column('character_race', sa.String(), nullable=False),
    sa.Column('character_class', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name=op.f('fk_characters_user_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=75), nullable=False),
    sa.Column('user', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name=op.f('fk_groups_user_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character', sa.String(), nullable=False),
    sa.Column('group', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['character'], ['characters.id'], name=op.f('fk_character_groups_character_characters')),
    sa.ForeignKeyConstraint(['group'], ['groups.id'], name=op.f('fk_character_groups_group_groups')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_groups')
    op.drop_table('groups')
    op.drop_table('characters')
    op.drop_table('users')
    # ### end Alembic commands ###
