"""fixing db.integer

Revision ID: 728239ab0a5c
Revises: b291a78e6908
Create Date: 2023-05-05 19:14:54.776465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '728239ab0a5c'
down_revision = 'b291a78e6908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
