"""fixit pls

Revision ID: b291a78e6908
Revises: 46d05bb0e36b
Create Date: 2023-05-05 14:11:12.847506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b291a78e6908'
down_revision = '46d05bb0e36b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_character_groups_character_characters', type_='foreignkey')
        batch_op.drop_constraint('fk_character_groups_group_groups', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_character_groups_group_id_groups'), 'groups', ['group_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_character_groups_character_id_characters'), 'characters', ['character_id'], ['id'])
        batch_op.drop_column('character')
        batch_op.drop_column('group')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(), nullable=False))
        batch_op.drop_constraint('fk_characters_user_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_characters_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('user')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_groups_user_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_groups_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_groups_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_groups_user_users', 'users', ['user'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_characters_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_characters_user_users', 'users', ['user'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('character_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('character', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_character_groups_character_id_characters'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_character_groups_group_id_groups'), type_='foreignkey')
        batch_op.create_foreign_key('fk_character_groups_group_groups', 'groups', ['group'], ['id'])
        batch_op.create_foreign_key('fk_character_groups_character_characters', 'characters', ['character'], ['id'])
        batch_op.drop_column('group_id')
        batch_op.drop_column('character_id')

    # ### end Alembic commands ###
